### ISSUE TITLE
TypeError: fd.isDirectory is not a function

### ISSUE THREAD

**Issue by valerii-cognite** [cognitedata/gearbox.js#248]
On latest master (a5abac47aee073131b8ec7ab33578f2371b7be77) I receive the following error during build

$ yarn clean && rollup -c && yarn esCheck
$ rm -rf dist
[!] TypeError: fd.isDirectory is not a function
TypeError: fd.isDirectory is not a function
    at fs.readdirSync.filter.fd (/Users/valgussev/Web/cognite/gearbox.js/rollup.config.js:17:14)
    at Array.filter (<anonymous>)
    at Object.<anonymous> (/Users/valgussev/Web/cognite/gearbox.js/rollup.config.js:16:4)
    at Module._compile (module.js:653:30)
    at Object.require.extensions..js (/Users/valgussev/Web/cognite/gearbox.js/node_modules/rollup/bin/rollup:1129:24)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

**Comment by xitman78** [comment]
Please read development section in the [https://github.com/cognitedata/gearbox.js#development](readme)

**Comment by valerii-cognite** [comment]
Thanks! Will it compile with apps running node 8?

**Comment by mrtraser** [comment]
This requirement (node version ^10.10) is only for building of gearbox bundle. When you use gearbox bundle in your application, you can use different version of node (including ver 8)
